name: SampleWorkflow

# Controls when the action will run. Workflow runs when manually triggered using the UI or API.
on: workflow_dispatch

env:
  AZURE_RESOURCE_GROUP: oardevol-hybrid
  CLUSTER_NAME: oardevol-kind
  
jobs:
  deploy_kubernetes:
    runs-on: ubuntu-latest
    steps:    
    - name: Login for az cli commands 
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
      
    - name: Get Azure SubscriptionId
      run: |
        CURRENT_SUBSCRIPTION_ID=$(az account show --query id -o tsv)
        echo "AZURE_SUBSCRIPTION_ID=$CURRENT_SUBSCRIPTION_ID" >> $GITHUB_ENV
        echo "Current SubscriptionId: $CURRENT_SUBSCRIPTION_ID"
    
    - name: Kubectl tool installer
      uses: Azure/setup-kubectl@v3

    - name: Run proxy
      run: |
        az config set extension.use_dynamic_install=yes_without_prompt
        az connectedk8s proxy --name $CLUSTER_NAME -g $AZURE_RESOURCE_GROUP > /dev/null 2>&1 &
        echo "Wating 30 secs for proxy to be up & running."
        sleep 30
        echo "Sleep done, invoking get pods!"
        kubectl get pods
